# ------ dataset_path ------
data_path: '/data/Public/Datasets/Caltech101/'

# ------ Hyperparamters ------
search_low: 0
search_high: 1
search_step: 50

# ------ Basic Config ------
dataset: 'caltech101'
shots: 16
backbone: 'RN50' # RN50 RN101 ViT-B/32 ViT-B/16

lr: 0.001
train_epoch: 100
batch_size: 64

# only 100 categories in the file 'split_zhou_Caltech101.json'
num_classes: 100

num_threads: 8
save_interval: 50

cache_dir: './model/clip'
