# ------ dataset_path ------
data_path: '/data/Public/Datasets/food-101/'

# ------ Hyperparamters ------
alpha: 0.5
search_low: 0
search_high: 1
search_step: 50

# ------ Basic Config ------
dataset: 'food101'
shots: 16
backbone: 'RN50' # RN50 RN101 ViT-B/32 ViT-B/16

lr: 0.001
train_epoch: 100
batch_size: 64

num_classes: 101

num_threads: 8
save_interval: 50

cache_dir: './model/clip'
