# ------ dataset_path ------
data_path: "/data/Public/Datasets/imagenetv2/imagenetv2-matched-frequency-format-val/"

# ------ Hyperparamters ------
alpha: 0.5
search_low: 0
search_high: 1
search_step: 50

# ------ Basic Config ------
dataset: 'imagenetv2'
shots: 16
backbone: 'RN50' # RN50 RN101 ViT-B/32 ViT-B/16

lr: 0.001
train_epoch: 100
batch_size: 128

num_classes: 1000

num_threads: 8
save_interval: 100

cache_dir: './model/clip'